[project]
name = "youqu3"
version = "0.1.0"
description = ""
authors = [
    {name = "mikigo", email = "huangmingqiang@uniontech.com"},
]
dependencies = []
requires-python = ">=3.7"
readme = "README.md"
license = {text = "GPL2.0"}

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
